// Copyright 2024 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated

pragma solidity ^0.8.20;

library ImageID {
    bytes32 public constant PERIOD_VERIFIER_ID =
        bytes32(0x7ce1e8993383063dd68c7e201bfb0032fd5818e5b0df0f240d1bdecb8f9c47f4);
    bytes32 public constant SIGNATURE_VERIFIER_ID =
        bytes32(0xe89b866a8242b30c83d480c0907757b429a2bf711b960adcd72436c3cdd9fe8b);
}
