// Copyright 2024 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated

pragma solidity ^0.8.20;

library ImageID {
    bytes32 public constant PERIOD_VERIFIER_ID =
        bytes32(0xa76c5439eafc81095da94cf5fbf2900e2a6885ab1b5936efb735967bb5060b93);
    bytes32 public constant SIGNATURE_VERIFIER_ID =
        bytes32(0x04cadee261895dcd63eeaa5e4509a7f035b5577ea2fab7c1f5172388c6ace801);
}
