// Copyright 2024 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated

pragma solidity ^0.8.20;

library ImageID {
    bytes32 public constant PERIOD_VERIFIER_ID =
        bytes32(0xadfc39ccb8055a51e09256e13fe74c98b3c018a18dfdb1e3eebcbed8eb51a494);
    bytes32 public constant PKCS7_VERIFY_ID =
        bytes32(0x1fdd66c125dc3a6467fa277002405704e62a74d4e47ffef7073e1e1b75d99435);
}
